name: 'Build & Release'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  build-release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2  # 3.2.2

        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1  # 1.115.3
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Deploy
        run: bash tools/deploy.sh
